"""sale draft status and discounts

Revision ID: b8063b7888b0
Revises: a4684394bc53
Create Date: 2026-04-08 01:58:19.322371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8063b7888b0'
down_revision = 'a4684394bc53'
branch_labels = None
depends_on = None


def upgrade():
    # Existing rows: treat as completed sales; subtotal mirrors legacy total.
    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.String(length=20),
                nullable=False,
                server_default="completed",
            )
        )
        batch_op.add_column(
            sa.Column(
                "subtotal",
                sa.Numeric(precision=12, scale=2),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "discount_percent",
                sa.Numeric(precision=5, scale=2),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "discount_amount",
                sa.Numeric(precision=12, scale=2),
                nullable=False,
                server_default="0",
            )
        )

    op.execute("UPDATE sales SET subtotal = total_amount WHERE subtotal = 0")
    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.alter_column("status", server_default=None)
        batch_op.alter_column("subtotal", server_default=None)
        batch_op.alter_column("discount_percent", server_default=None)
        batch_op.alter_column("discount_amount", server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_percent')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
